server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: "postgres"
    password: "root"
    url: "jdbc:postgresql://localhost:5432/examination_platform"